### ISSUE TITLE
2018年の記事の Copyright が2017でいいの？

### ISSUE THREAD

**Issue by matsubara0507** [haskell-jp/blog#104]
と友人に言われた。
正しくは 2018 ?? それとも 2017-2018 ??
[問題の箇所](https://github.com/haskell-jp/blog/blob/master/preprocessed-site/templates/default.html#L130)

**Comment by kakkun61** [comment]
ライブラリーとかは追記部分もリリース年でいいらしい（会社の法務がそう言ってた
ブログは……？
あと、実はその部分に法的な決まりはないらしい

**Comment by igrep** [comment]
https://liginc.co.jp/designer/archives/11313 も読む限り発行年っぽいですね。。。
記事ごとに設けるとなるとちょっと面倒ですな。

**Comment by matsubara0507** [comment]
確かに、igrep 氏のリンクにも法的な能力は無いらしいですね。
記事ごとに埋め込むのは Context を足すだけなので難しくないとはあ思いますよ。
やってみます。

**Comment by matsubara0507** [comment]
`index.html` は 2017 ?? 2018 ?? どっちだろ？

**Comment by matsubara0507** [comment]
> まとめ
> コピーライト文は書かなくてもOK。（でも慣習などから見て書いた方が無難）
> 文に必要な要素は「©」「最初の発行の年」「著作権者の氏名」だけ。

ってことは 2017 でいいかな

**Comment by igrep** [comment]
> 確かに、igrep 氏のリンクにも法的な能力は無いらしいですね。

あ、念のため補足するとその点では全くないわけではないです。
[Wikipedia](https://ja.wikipedia.org/w/index.php?title=%E8%91%97%E4%BD%9C%E6%A8%A9&oldid=67356969#%E8%91%97%E4%BD%9C%E6%A8%A9%E3%81%AE%E7%99%BA%E7%94%9F%E8%A6%81%E4%BB%B6)ではこのように述べています。

> コピーライトマーク「©」は、著作権の発生要件として著作物への一定の表示を求める方式主義国において、要件を満たす著作権表示を行うために用いられるマークである[8]。
> 一方、日本などの無方式主義を採る国においては著作物を創作した時点で著作権が発生するため、著作物に特定の表示を行う義務は課されていない。しかし、著作権は各国ごとに発生するため、無方式主義国における著作物でも、方式主義国において著作権保護を得るためにはその国での著作権の発生要件を満たす必要があり、このマークを付すことが一般的に行われていた。

**Comment by igrep** [comment]
デプロイもされたのでclose
