### ISSUE TITLE
コードブロックに下線が入る

### ISSUE THREAD

**Issue by igrep** [haskell-jp/blog#106]
いつから入るようになったんだろう。。。

スクショは直近の記事 https://haskell.jp/blog/posts/2018/windows-long-path.html より。

![windows haskell no such file or directory - haskell-jp - google chrome 2018_03_28 16_17_00](https://user-images.githubusercontent.com/227057/38014375-8ad247aa-32a3-11e8-9e44-73d2e9c0bd91.png)

発生した環境 (Windows 10 64bitのChrome 65):

```
> navigator.userAgent
"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36"
```

**Comment by igrep** [comment]
同じ記事より。シンタックスハイライトがかかっているブロックだけ下線が入るみたいです。

![windows haskell no such file or directory - haskell-jp - google chrome 2018_03_28 16_18_01](https://user-images.githubusercontent.com/227057/38014415-adbe0cae-32a3-11e8-91f2-c6902074db7f.png)

**Comment by matsubara0507** [comment]
Hakyll のバージョンをあげたときかな…？
たしか、いつぞやのバージョンアップでコードハイライト(や箇条書きとか)のHTMLの構成が変わった気がする。
正確には Hakyll ではなく Pandoc かな？

**Comment by matsubara0507** [comment]
このあたりが実際の差分
https://github.com/haskell-jp/blog/commit/def8dc2d7861e9021634470f752f03aed2a32c88#diff-811d20332d987abc9794933f623c0111L182

**Comment by matsubara0507** [comment]
css をいじるか、hakyll の方をいじるか(hakyll でなんとかなるのかは分からない…)

**Comment by matsubara0507** [comment]
@igrep クローズしちゃってもいいですか？

**Comment by igrep** [comment]
そうでした。クローズしてください！

**Comment by matsubara0507** [comment]
#108 で修正した
