### ISSUE TITLE
Twitterカードが変なところで切れている

### ISSUE THREAD

**Issue by igrep** [haskell-jp/blog#114]
例:

![fireshot capture 1](https://user-images.githubusercontent.com/227057/39745450-3d9c4594-52e2-11e8-86ca-f00a56ae3804.png)

sakulambdaだけが出るようにするとか、工夫が必要そう。

**Comment by igrep** [comment]
こちらですが、表示する画像を https://github.com/haskell-jp/logo/blob/master/logo-avator.png に変えたり、Twitterカードの仕様を確認して、適切なアスペクト比の画像を出すようHTMLを書き換えることで解決できるのではないかと踏んでいます。

**Comment by takenobu-hs** [comment]
Twitterカードの仕様を見てみたのですが、「Summary Card」仕様の方は、画像の縦横比が1:1の固定のみのようでした。
（「Summary Card with Large Image」仕様は2:1まで可能なようですが、投稿本文の表示領域が小さくなるので、1:1固定になりますが「Summary Card」仕様の方が良いと思います。）

Optimize Tweets with Cards
https://developer.twitter.com/en/docs/tweets/optimize-with-cards/overview/summary.html

ということで、画像そのものを、縦横比1:1の正方形で作って配置するのが適切の模様です。
で、今のfaviconのように、サクラムダ部分のみを抽出するのも良いですが、やはり、"Haskell-jp"のデザインもかっこ良いので、ここも表示させたいと思います。

そこで、少々強引ですが、縦配置のサクラムダ（タテラムダ？）を仮に作ってみました。
オリジナルデザイナーのfumiさんのデザイン意図もあると思いますので、皆さん、コメント頂けますか？
（サクラムダ部分だけで良いとか、配置をもっとこう寄せろとか、大きさを変えろ、とか^^  遠慮せずこだわって下さい。）

イメージを以下↓に貼り付けます。

**Comment by takenobu-hs** [comment]
![logo-1200x1200](https://user-images.githubusercontent.com/9017980/42409778-4b76ce98-821a-11e8-822d-e398c4f3ed64.png)

**Comment by takenobu-hs** [comment]
まだ、図柄を確認してもらいたいので、issueをcloseしないで、openにしておきます。

**Comment by takenobu-hs** [comment]
#130 のmergeで、背景を白にした図形を登録しました。
登録したimageがtwitterのサイトに反映されて伝搬するまでは時間がかかるそうなので、しばらく様子見します。

imageの図柄に改善案等があれば、コメントをよろしくお願いします。

**Comment by igrep** [comment]
いい感じですね！
https://twitter.com/igrep/status/983183658117824512
![image](https://user-images.githubusercontent.com/227057/42418417-fea01018-82da-11e8-96b0-339c9db00b55.png)

@fumieval 何かご意見があればよろしくお願いします。問題なければそのままマージで！

**Comment by fumieval** [comment]
これでよいと思います！ :+1:

**Comment by takenobu-hs** [comment]
有難うございます！ :+1: 
では、このissueはcloseしておきますね。
