### ISSUE TITLE
コードブロックのスタイル崩れ

### ISSUE THREAD

**Issue by wat-aro** [haskell-jp/blog#134]
https://haskell.jp/blog/posts/2018/derive-json-no-prefix.html

`.sourceCode` に `overflow: visible` が当たっているために、要素が幅をこえた場合に背景がずれてしまっています。
`pre.sourceCode`を`overflow: auto`または`overflow: scroll` に変更すると直りそうです。

[![Image from Gyazo](https://i.gyazo.com/15630fc5f2e664ece47d554a8a49f83f.gif)](https://gyazo.com/15630fc5f2e664ece47d554a8a49f83f)

**Comment by igrep** [comment]
ご連絡が遅くなりました。
本件、こちらのCSSを直せばよい問題ではなく、多分に https://github.com/jgm/skylighting の問題と思われるので、よければ報告していただけると幸いです 🙏

**Comment by igrep** [comment]
英語が厳しいとかであれば私がやるか次の https://docs.google.com/spreadsheets/d/1R3cqln4mCAL_7Gr6hdJueHnwxYFmenGrWLGMSQPEKnI/edit#gid=1386834576 に流します。 🙇
