### ISSUE TITLE
全文検索の追加

### ISSUE THREAD

**Issue by mizunashi-mana** [haskell-jp/blog#136]
[hacktoberfest 2018](https://hacktoberfest.digitalocean.com/)の一環で、ブログに全文検索エンジンをつけてみようと思うのですが、どうでしょう？

とりあえず精度とかあまり考えずlunr.jsで、prebuilding indexを生成するスクリプトと、検索画面を作ってみようかなと考えています
https://lunrjs.com/guides/index_prebuilding.html

**Comment by igrep** [comment]
ほぉ！2点気になります。

1. Google Custom Searchに敢えてしないのは、純粋に取り組んでみたいから？
1. つまるところindex情報の保存は https://github.com/haskell-jp/blog/tree/gh-pages に直接保存してXHRなりFetchで取り出す、ってことになるんですかね？

**Comment by mizunashi-mana** [comment]
> Google Custom Searchに敢えてしないのは、純粋に取り組んでみたいから？

あ、別にGoogle Custom Searchでも構いません。アカウントを用意してもらえればそっちでも構わない感じです。

> つまるところindex情報の保存は https://github.com/haskell-jp/blog/tree/gh-pages に直接保存してXHRなりFetchで取り出す、ってことになるんですかね？

そうですね。インデックス情報をgh-pagesブランチに保存して、検索画面から保存したインデックスをJavaScriptで読み込む感じになると思います。

**Comment by mizunashi-mana** [comment]
了解です．では検索エンジンの追加は無しで
