### ISSUE TITLE
Copyrightの日付表示について

### ISSUE THREAD

**Issue by mizunashi-mana** [haskell-jp/blog#142]
いちよSlack上で上がったので，ここにもトラッキングしておきます．

UCC III-1 (http://portal.unesco.org/en/ev.php-URL_ID=15381&URL_DO=DO_TOPIC&URL_SECTION=201.html) にある通り:
> ..., if from the time of the first publication all the copies of the work published with the authority of the author or other copyright proprietor bear the symbol © ac-companied by the name of the copyright proprietor and the year of first publication placed in such manner and location as to give reasonable notice of claim of copyright. 

国際法上，通常は制作年が書かれていればコピーライト表示は有効です．しかし，メンテナンスが行われているかの通知のため，慣習的に [制作年]-[本年] という表示で毎年更新していく場合も多いです．

これを踏まえて，
1. 現在の表示(2017)のままにする
2. 2017-2018と書き毎年更新を行う
3. その他

のいずれにするか明確化しておくのがいいと思います．

P.S.

元々の問題提起は，blogに対してだったんでここにイシューを建てたんですが， https://github.com/haskell-jp/community の方が良かったですかね？

**Comment by mizunashi-mana** [comment]
個人的には国際法上問題なく，この慣習にも違反しない(ただし，更新を止める場合その止めた年を明記するのを忘れないようにする必要はある) [制作年]- という表示が好きです．

**Comment by igrep** [comment]
私の観測範囲で、ですが、「[制作年]-」という表記をあまり見たことがなく、単純に更新年の箇所を書き忘れたように見えてしまうんじゃないか、と感じたので更新年付け足したいと思います。
どちらにしても毎年ブログを続ければいいだけのこと！

**Comment by igrep** [comment]
> 元々の問題提起は，blogに対してだったんでここにイシューを建てたんですが， https://github.com/haskell-jp/community の方が良かったですかね？

そうですね、今回はここで完結させてしまいますが、 haskell-jp.github.ioのリポジトリーも絡んでますし、今後はcommunityの方で議論しましょう。
