### ISSUE TITLE
gh pages を docs で公開する提案

### ISSUE THREAD

**Issue by kayhide** [haskell-jp/blog#18]
いまは `gh-pages` ブランチを使っていますが、`docs` ディレクトリで公開する方法はいかがでしょうか？
https://help.github.com/articles/configuring-a-publishing-source-for-github-pages/#publishing-your-github-pages-site-from-a-docs-folder-on-your-master-branch

この方式だと、生成された `generated-site` をリネームするだけでいけますのでお手軽です。

**Comment by arowM** [comment]
@cdepillabout, 
`gh-pages`ブランチをつかったのって、メインのブランチに生成後のファイルを含めたくなかったとか、なにか理由ありますか？

**Comment by cdepillabout** [comment]
@arowM 特に理由はないです。 `docs` を使ってもいいと思います。

**Comment by igrep** [comment]
こちら、 `gh-pages` ブランチを使った方法でデプロイするところまで定着しているので、closeさせていただきます。
これから運用を変えるのはちょっとしんどいです。
やっぱり生成物はmasterブランチに含めたくない、ということで。

**Comment by igrep** [comment]
何かご意見あればお気軽にreopenしてください。
