### ISSUE TITLE
相互リンク作成依頼：（roki.log）

### ISSUE THREAD

**Issue by falgon** [haskell-jp/blog#195]
https://roki.dev/roki.log/

運営者の氏名（ハンドルネーム可）: Roki

もしよろしければ, よろしくお願い致します。:bow:

**Comment by igrep** [comment]
✅ 承認します！
 👇 のスニペットを https://roki.dev/roki.log/ の適当な箇所に貼り付けてください。

```html
<a href="https://haskell.jp/blog/posts/links.html#roki.dev/roki.log/"><img width="234" src="https://haskell.jp/img/supported-by-haskell-jp.svg" alt="Supported By Haskell-jp."></a>
```

**Comment by igrep** [comment]
https://roki.dev/roki.log/ の更新を確認でき次第 ☝️ のPull requestをマージします。

**Comment by falgon** [comment]
ありがとうございます！下部フッター部分に追加いたしました。

**Comment by igrep** [comment]
LGTM!
![ありがとうございました](https://user-images.githubusercontent.com/227057/91381876-5b562500-e863-11ea-85c7-63d382179a8e.jpg)
