### ISSUE TITLE
haskell-jp-bot の通知を受け取りたくない

### ISSUE THREAD

**Issue by Hexirp** [haskell-jp/blog#205]
このリポジトリの問題なのか、それとも GitHub の使い方の問題なのか……どちらなのか分かりませんが、いちおうこちらに立てておきます。

haskell-jp を watch していますが、 haskell-jp-bot のビルド・プレビューの結果の URL のコメントがたくさん通知に現れています。その割合は、体感としては普通のコメントの 4 倍ぐらいです。うざったいなという感じです。

これをフィルターしたりすることは出来るでしょうか？

**Comment by igrep** [comment]
最近のGitHubだと、 👇 の設定画面でwatchする項目を選べるようになっているのでそこでコミットに対するコメントを除外できれば... と思いましたが、現状コミットへのコメントをoffにする機能はないみたいですね...

![image](https://user-images.githubusercontent.com/227057/111593223-13055100-880d-11eb-9237-c98c2cf5a203.png)

**Comment by Hexirp** [comment]
うーん、とりあえず我慢するしかない感じですね。

**Comment by Hexirp** [comment]
たとえば、 https://app.circleci.com/pipelines/github/haskell-jp/blog/69/workflows/0daa7548-bef0-4235-b788-44468b702936/jobs/875/artifacts みたいなページから各自で見るという感じで行けませんか？ いや、不親切になりすぎますね。（そういえば、 Circle CI のログってログインしないと見れないようになったんですね）

**Comment by igrep** [comment]
☝️  の設定項目のなかでコミットへのコメントがどれに分類されているのか不明瞭なので、もしかしたら例えば「Issues」「Pull requests」のみを選択するとコミットへのコメントが除外されないかな... と今推測しています。
つまり「コミットへのコメント」は4つの設定項目のうちどれでもなさそうなので、Watchの設定を「Custom」にしているうちはどれも該当しないのではないか、と。

**Comment by Hexirp** [comment]
そうしてみます。これで解決するか試すためには時間が掛かりそうですが。

**Comment by Hexirp** [comment]
他の人にコミットに対してコメントしてもらえばすぐに試せるかも？

**Comment by igrep** [comment]
試しに少し時間が経ってから（余裕を持って1日ぐらい待ってみましょうかね）、すでに送られているPull requestに含まれるコミットに私がコメントしてみます。それで @Hexirp さんに通知が来なければhaskell-jp-botのコメントも来ないはず。

**Comment by Hexirp** [comment]
了解です。

**Comment by Hexirp** [comment]
@igrep 通知がありませんでした。ありがとうございます！
