### ISSUE TITLE
haskell-jp-bot のGitHub Personal Access Token

### ISSUE THREAD

**Issue by igrep** [haskell-jp/blog#209]
GitHubから、 @haskell-jp-bot が使用しているPersonal Access Tokenを新しい形式に更新せよ、とのメールが来ました。そういえばこいつもPersonal Access Tokenを使ってましたね。

このアカウント、私が使用しているものを含めいくつかのPersonal Access Tokenを使ってまして、そのうち一つの名前が「haskell-jp-blog-preview-bot」とあるとおり、当リポジトリーのビルド時にレビュー用URLをコメントするために使われているようです。CircleCIの設定を見た限り、件のPersonal Access Tokenは haskell-jp-blog-artifact.herokuapp.com が参照していると思われるのですが、合ってますか？もしそうであれば、新しいPersonal Access Tokenを発行して送るので書き換えてください。 @fumieval 

再生成後は古いPersonal Access Tokenが使えなくなり、haskell-jp-botが動かなくなるので同じタイミングでやりましょう。

**Comment by fumieval** [comment]
@igrep 遅くなってすみません。

はい、`haskell-jp-blog-artifact`は私が管理しており、`GITHUB_TOKEN` = `token 5f6...`の形式で設定されています。新しいトークンを生成していただければ、こちらで更新します。
