### ISSUE TITLE
投稿の背景画像が重い

### ISSUE THREAD

**Issue by fujimura** [haskell-jp/blog#35]
1MB以上あるので、軽いものに差し替えたほうがよさそうです。

<img width="2133" alt="screen shot 2017-08-09 at 15 03 53" src="https://user-images.githubusercontent.com/134072/29107412-1fa754dc-7d15-11e7-963a-cee04602a931.png">

**Comment by nobsun** [comment]
blog のトップページにある富士山の写った写真はあまり好きになれません。富士山はいいとして、五重の塔の意匠があまりにアレで、これが日本の象徴的風景として紹介されるのはかなり残念な気がしてしまいます。代替の画像を提案できるわけではないので、単なる感想です。ちょっとキッチュ感を強く感じたもので。

**Comment by igrep** [comment]
@nobsun すみません、変えたいならば別issueでお願いします。
ここはそこを議論するところではないです。
あるいは単なる愚痴であればslackで。

**Comment by nobsun** [comment]
失礼しました。

**Comment by igrep** [comment]
https://github.com/haskell-jp/blog/pull/111 によって、背景画像はなくなりました。
