### ISSUE TITLE
Typo の報告

### ISSUE THREAD

**Issue by lesguillemets** [haskell-jp/blog#45]
こんにちは，どこに報告すべきかちょっと迷ったのですが…

[「About kind system of Haskell (Part 1) 種の仕組みとそれに付随する言語拡張について」](https://haskell.jp/blog/posts/2017/10-about-kind-system-part1.html) のなかに Part 2 へのリンクが2箇所あるのですが，リンク先が間違っているようです．

誤 : `12-about-kind-system-part2.html`
正 : `13-about-kind-system-part2.html`

**Comment by igrep** [comment]
ありがとうございます！もしよければ直接 https://github.com/haskell-jp/blog/edit/master/preprocessed-site/posts/2017/13-about-kind-system-part2.md で編集してPull requestを送っていただけると助かります！

**Comment by lesguillemets** [comment]
すみません，素早く対応頂いてたのに色々で反応できませんでした．次回からこういうことがあれば pull-req 送らせていただきます．ありがとうございました
