### ISSUE TITLE
デプロイと記事プレビュー環境の改善

### ISSUE THREAD

**Issue by igrep** [haskell-jp/blog#50]
https://github.com/haskell-jp/blog/issues/18 とか、ここ何本かの記事のレビューやデプロイを通して感じた下記の対応したいと思います。

1. 手でデプロイするのはしんどい
    - CIでデプロイさせる
1. レビュー時に、ビルド(`make build`)後の記事の見た目を確認するのが面倒
    - PRを送られた時点でCIが対象の記事に`draft: true` を加えてデプロイできるようにする
    - PR送った時点で完全に自動でデプロイするのはさすがに危険なので、何かしら手でのトリガーを考える

実現方法など、ご意見募集します！

**Comment by igrep** [comment]
https://github.com/haskell-jp/blog/issues/18 については、デプロイ方法を単純化する方法の一つとして検討しています。

**Comment by igrep** [comment]
２つめの問題を解決するに当たり、docディレクトリーを使った方法と従来通りgh-pagesブランチを使った方法、どっちがいいんだろうなぁ。。。

**Comment by igrep** [comment]
そうか、今でも現在checkoutしているブランチにいるときに `make deploy` すればgh-pagesでデプロイするようになっているみたいだし、別に今のままでいいかも。

**Comment by matsubara0507** [comment]
Circle CI でビルドして artifacts に HTML を置いて確認
ってのは微妙かしら？

**Comment by igrep** [comment]
ちょっと手間がかかるけど、悪い案ではないですね。

**Comment by igrep** [comment]
とりあえず、従来通りgh-pagesブランチで自動デプロイする方法を試してみます（有言実行）

**Comment by igrep** [comment]
> レビュー時に、ビルド(make build)後の記事の見た目を確認するのが面倒

こっちの方ちょっと考えたんですが、こんな方法がいいんじゃないかと思っています。

1. 何らかのキック（ `PREVIEW_BUILD` みたいな適当な環境変数をオンにする？）
1. preview用のブランチをmasterから切り、対象のPRをmergeする
1. preview用のブランチ上で、対象の記事のmetadataに `draft: true` を追記する
1. preview用のブランチをビルドし、デプロイする

**Comment by igrep** [comment]
📝 CircleCIが手動での実行をサポートしたそうで、もしかしたら使えるかも知れません。
https://circleci.com/blog/manual-job-approval-and-scheduled-workflow-runs/
ただ、Travis CIからの移行が必要なので選択肢としての優先順位は低いですが。

**Comment by igrep** [comment]
@matsubara0507 
> Circle CI でビルドして artifacts に HTML を置いて確認
ってのは微妙かしら？

あ、ごめんなさい。この方法ちょっと誤解してた。
そうだ、ありましたね。Circle CIのartifacts機能。
`preview: true` にするよりも楽そうです！ 👍

**Comment by igrep** [comment]
Travis CIだとS3のアカウント（つまり有料）が別途要るのか。悩ましい。
https://docs.travis-ci.com/user/uploading-artifacts/
https://circleci.com/docs/2.0/artifacts/

**Comment by igrep** [comment]
まだCricleCIからデプロイできてないとか細々した問題はありますが、最低限artifactsを閲覧できることは確認したので、これで解決とします（デプロイはTravis CIからもできてますしね）。
