### ISSUE TITLE
Circle CIからデプロイできない

### ISSUE THREAD

**Issue by igrep** [haskell-jp/blog#54]
https://github.com/haskell-jp/blog/pull/53 で何度かビルドしていて気づいたのですが、 https://circleci.com/gh/haskell-jp/blog/30 のように、どうもCircle CIからデプロイしようとすると、CIRCLE BUGにはまってしまうようです。Circle CIに問い合わせよう。

**Comment by igrep** [comment]
報告完了 https://discuss.circleci.com/t/circle-bug-when-pushing-to-gh-pages/18353

**Comment by mizunashi-mana** [comment]
とりあえずそれまではtravisをmaster onlyで使うのはどうでしょう？ PRはcircle ciオンリーでやることにして

**Comment by igrep** [comment]
はい。そうですね。。。当面はそれでいきましょう。
設定も変えるか。

**Comment by igrep** [comment]
@nakaji-dayo 
補足し忘れてました。
https://github.com/haskell-jp/blog/pull/113 でCircle CI 2.0に移行したことにより、同じ問題が発生しなくなっている可能性がありますので、その辺を試していただきたいです。

**Comment by nakaji-dayo** [comment]
こちらの問題再現しないようになっていました。
circle ci 2.0でのdeployを含むworkflowを作りした。
travisは停止していただき、設定も削除しました。
