### ISSUE TITLE
README日本語版の標準化

### ISSUE THREAD

**Issue by mizunashi-mana** [haskell-jp/blog#58]
README.mdは日本語版の方がリポジトリトップにあった方が(現状は英語版の方が出ていますが)，とっつやすいのではないでしょうか？

**Comment by igrep** [comment]
デプロイ方法などもう普通のユーザーは知らなくてもいいですもんね！
刷新しましょう。

**Comment by igrep** [comment]
https://github.com/haskell-jp/blog/pull/56/commits/1eb50d9b45059846c294dae649ac0da2cf698a19 で、従来のREADMEを思い切ってバッサリ捨て、READMEに投稿方法を集約させる方向で修正しました。

**Comment by mizunashi-mana** [comment]
👍
