### ISSUE TITLE
（意見募集）記事の権利の帰属について

### ISSUE THREAD

**Issue by igrep** [haskell-jp/blog#59]
現状、[LICENSE](https://github.com/haskell-jp/blog/blob/2c0366a97d4c52ff37ceddb2a5f9314cfce29f94/LICENSE)をみるとMITが適用されていますが、これは記事のライセンスではなく `site.hs` やCSSなど、ウェブサイトの構成についてのライセンスであるという認識です。

この点、これから寄稿を増やす上で明示しておいた方が無難でしょうし、Issueとして登録しておきます。

**Comment by igrep** [comment]
基本的には、著作権は我々日本Haskellユーザーグループではなく、記事を書いた本人に帰属させるという方針がよいと思っていますが、いざというときのことを考え、何かしら特別な条項を設けた方がいいかもしれません。

どなたかご意見があればよろしくお願いします。

**Comment by mizunashi-mana** [comment]
Haskell Wikiと同じライセンスでいいのではないでしょうか？
https://wiki.haskell.org/HaskellWiki:Copyrights

**Comment by igrep** [comment]
@mizunashi-mana 中身詳しく読んでないんですけど、なぜそう思いました？

**Comment by mizunashi-mana** [comment]
このライセンスは俗にMITライセンス(またはExpat License)と呼ばれるものですね．以下に邦訳を置いておきます．

> Permission is hereby granted, free of charge, to any person obtaining this work (the "Work"), to deal in the Work without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Work, and to permit persons to whom the Work is furnished to do so.
> 
> THE WORK IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE WORK OR THE USE OR OTHER DEALINGS IN THE WORK. 

> 以下に定める条件に従い、この著作物（以下「ワーク」）の複製を取得するすべての人に対し、「ワーク」を無制限に扱うことを無償で許可します。これには、「ワーク」の複製を使用、複写、変更、結合、掲載、頒布、再許諾、および/または販売する権利、および「ワーク」を提供する相手に同じことを許可することも含まれます。 
>
> 「ワーク」は「現状のまま」で、明示的であるか暗黙的であるかを問わず、何らの保証もなく提供されます。ここでいう保証とは、商品性、特定の目的への適合性、および権利非侵害に制限されず，如何なる保証をも含みます。 作者または著作権者は、契約行為、不法行為、またはそれ以外であろうと、「ワーク」に起因または関連し、あるいは「ワーク」の使用またはその他の扱いによって生じる一切の請求、損害、その他の義務について何らの責任も負わないものとします。

Haskell-jp BlogはHaskell Wikiと性質が似ているので(投稿する人が限られないこと/特に内容の信憑性が高く無いこと/一般公開であること)，手っ取り早くHaskellで繋がりで実績のある(Haskell Wikiはある程度アクセスはあると思うので)ものを持ってきた感じです．

**Comment by igrep** [comment]
うーん、Wikiと違って、原則として著作者が名前を示して著作者の作品として提示しているので、繰り返しますが記事自体の権利は書いた人のものとしたいです（その上でCC系のライセンスを適用することを求める、といったことはありだと思います）。

あとそのライセンス、普通明示すべき、誰が著作権の保有者なのか明記してませんし、そもそも内容からして読む人向けのライセンスなので、あまりにも不明瞭だと思います（察するにHaskellWikiに権利を渡して、HaskellWikiがMITで利用者に提供する、ということなんでしょうけども）。

まぁ、いずれにしてもあんまりみんな気にしてないってことなんでしょうけど。。。
（現に我々自身後回しにしているわけですし）

**Comment by mizunashi-mana** [comment]
MITは元々コントリビュートなどの規定は曖昧なので、権利保有者は明確な記述が無いならその著作者ということになります(なので対象がページ内容でなく「ワーク」なのでしょうが)

僕の記事に関していえば免責事項付きならパブリックドメインでもいいので、CC系ならどのレベルでも賛成です

**Comment by arowM** [comment]
もともとの問題提起が
> これから寄稿を増やす上で（記事のライセンスを）明示しておいた方が無難
とのことなので、
* ライセンスとしては @mizunashi-mana さんのご説明のとおり問題なさそうなMITライセンスのままにしておく
* 別途 `CONTRIBUTING.md` とか README とかの「寄稿しようかな〜」って人が気づきやすい場所に「安心してください！ MITライセンスでも記事自体は寄稿してくださったあなたが著作権保有者です！」みたいに明記しておく
ってしておくと良さそうですね〜

**Comment by igrep** [comment]
> MITは元々コントリビュートなどの規定は曖昧なので、権利保有者は明確な記述が無いならその著作者ということになります(なので対象がページ内容でなく「ワーク」なのでしょうが)

お、すみません、誤解してました。
なるほど。

> ライセンスとしては @mizunashi-mana さんのご説明のとおり問題なさそうなMITライセンスのままにしておく

すみません、ちょっとCCと両方比較させてください。

> 別途 CONTRIBUTING.md とか README とかの「寄稿しようかな〜」って人が気づきやすい場所に「安心してください！

今はREADMEに寄せようとしているところなので、READMEに書く予定です。
あと、フッターにあるコピーライトの表記も変えなきゃですね。

**Comment by igrep** [comment]
@takenobu-hs そうそう、過去に投稿していただいたたけのぶさんは何かご意見ありますか？
必要であれば個別の対応は検討しますが、原則として過去の記事にも適用する予定なので、念のため。

**Comment by takenobu-hs** [comment]
@igrep 私の記事については、個人著作でもhaskell-jpのものでも良いですし、ライセンスもMIT、CCなどでも良いです。 特にこだわりなしです。

haskell-jpのblogサイトについては、いろんな人に気軽に書いてもらうという意味では、議論されている方針で良いと思います。
（サイトの基本的な方針から変更したい人には、その記事毎に別のライセンスに従いたいことを明記してもらってもよいかもしれませんね。）

**Comment by igrep** [comment]
よくよく考えたら、どうせ個別対応をよしとするのであれば、デフォルトはどれでもいいっちゃどれでもいい気がしてきました。

ともあれ、常に個別対応が必要みたいな状況は困るので、デフォルトを決めるべくHaskellWikiのライセンスと[CC-BY](https://creativecommons.org/licenses/by/4.0/legalcode.ja)を読み比べてみたのですが、やはり

- MITがカバーしている領域は、すべてカバーしている *はず*（無保証の部分とか）
- プログラム以外の、普通の著作物のライセンスについて、世界でよく使われ、よくメンテされている（継続的にアップデートされるであろう）

といった点を考慮して、やっぱりCC-BYがいいんじゃないかと思っています。
MITとほぼ同じぐらいの緩さですし。
唯一大きく違うのは、再配布の場合に元の著作者の名前の表示義務などがある点です。
Haskell Wikiと異なり、Haskell-jp Blogは、あくまで個人の作品として独立した記事を書く場を提供することで、個人のHaskellコミュニティーでの知名度を高めるのをサポートしたい、という狙いもあるため、重視したい部分です。

**Comment by igrep** [comment]
> Haskell Wikiと異なり、Haskell-jp Blogは、あくまで個人の作品として独立した記事を書く場を提供することで、個人のHaskellコミュニティーでの知名度を高めるのをサポートしたい、という狙いもあるため、重視したい部分です。

まぁ、この部分についてはぶっちゃけると「私がそうしたいから」に他ならないのですがw

**Comment by kakkun61** [comment]
デフォルト CC-BY いいと思います。

**Comment by mizunashi-mana** [comment]
コントリビュートの場合，現状Haskell-jpは名前を明記していない(著者しか表示されていない)ですが，コントリビュータに関しての翻案ライセンスはどういう扱いになるんでしょう？

**Comment by igrep** [comment]
すでにある記事に大幅な加筆修正とかをした場合ですかね？
誤字脱字程度の軽微な修正であれば特に何も出さなくてもいいと思うのですが、
必要に応じて（コントリビュータの希望に応じて）著者に加える、とかかなぁ。

**Comment by igrep** [comment]
ああ、翻訳記事であればちょっと個別の対応が必要になりますね。

**Comment by mizunashi-mana** [comment]
いえ権利の帰属の問題で，修正した箇所のライセンスは修正者にありその場合もCC-BYを適用すると思うのですが，その場合修正者がHaskell-jp Blog読者の分かるところにないとCC-BYは適用しづらいと思うのですがどうなるのでしょう？ という感じです

**Comment by igrep** [comment]
共著者として加える、というのではダメなんですか？

**Comment by mizunashi-mana** [comment]
「コントリビュータの希望に応じて」と書いてあったので通常は加えないものだと思ってたのですが，

* 通常コントリビュートもCC-BYを適用し共著者にコントリビュータの名前も加える．
* CC-BYでなくコントリビュータが希望で別のライセンスを所望する(例えば，コントリビュータの権利を放棄し修正箇所は原著者に帰属させることを希望する)場合などには，希望に合わせて共著者には加えない

ということなら，賛成です．

**Comment by mizunashi-mana** [comment]
あ、いちよなんですが、これは個人的心情からくるものではなく(僕は特にコントリビュータの権利にこだわりはないです)、CC-BY 4.0の規定からくる留意点としての意見です。

CC-BY 4.0では明確に翻案物を規定しており(1.a これには改変、編集も含まれます)、コントリビュートにCC-BYをそれは翻案物に関するライセンス適用でありそのライセンスは翻案者のライセンスということになります(1.b)。

翻案者のライセンスはCC-BY 4.0では元のライセンス(つまりCC-BY 4.0)と互換のあるものでなければなりません(3.4)が、その範囲なら自由に決めることができます。

今回は翻案者のライセンスをデフォルトでCC-BY 4.0(+ copy right holderは原著者とコントリビュータ)とするという方針と認識していますが、その場合翻案物利用者には権利者の表示義務が発生します。もし、コントリビュータの記載がHaskell-jp Blogにない場合利用者はgitのログを見に行き権利者を特定し表示する必要があります。また、Haskell-jp Blogの表示だけをみて表示責任を果たした場合、ライセンス違反になる可能性があります。

それはライセンス運用として正しいあり方では無いと思うので、運用体制を変える必要があるのでは？ というのが上の意見です

**Comment by mizunashi-mana** [comment]
(なお個人的には、別にコントリビュータの権利に関してはこだわりがないので、原著者に帰属させる運用でもいいと思いますし(これはCC-BY 4.0と互換があるので)、それ以外の体制でもいいです。ただ、原著者に帰属させる場合、原著者の免責として原著者には、それを拒否しコントリビュートに関してはコントリビュータの著作物とする権利を認めて欲しいですが)

**Comment by igrep** [comment]
@mizunashi-mana ありがとう、見落としていた視点でした！
やっぱり触れたとおり、原則として、コントリビューターに当たる人は共著者として `author` に書き加える形で行こうと思います。もし元著者とコントリビューターを区別したいというニーズがあった場合はmetadataとして新たに書き加えることで。

ただ、typoや細かい言い回しの変更など、内容の変更に大きく関わらない修正は、慣習上共著者には加えない、という方針にしたいと思います。
（線引きが難しくなるケースがあるかも知れませんが）
法的に適切かは確信が持てませんが、都度加えるような運用だと明らかに煩雑になってしまうし、それでtypoの修正が滞るというのも本末転倒なので。

みんなで自由に書き換える、というようなコンテンツは基本的にHaskell-jp Wikiに書くことを推奨しているので、この運用であれば、コントリビューションの規定を運用することはそうそう頻繁にない（はず）です。

**Comment by igrep** [comment]
Slackで話し合ったとおりですが、CC-BY 4.0の仕様上、「小さな変更」についても改変に該当するそうなので、問題を単純にするため、既存の記事についての（元著者以外による）加筆・修正は、すべて元著者に委譲する、ということにします。
ただし、原則としてPull requestのレビューなどを通して、元著者の同意の下で委譲する、ということにします。
それなら、レビューの指摘などでの修正が事実上元著者の作品として適用されている、現在の実態に合うでしょうし。

**Comment by igrep** [comment]
後はルールを記載する場所ですが、`CONTRIBUTEING.md` に加え、 `PULL_REQUEST_TEMPLATE.md` でも `CONTRIBUTEING.md` への案内を出すのがいいんじゃないかと思っています。
いちいち消すのが面倒ですけどね。

https://github.com/blog/2111-issue-and-pull-request-templates

**Comment by mizunashi-mana** [comment]
Resolvedですかね？

**Comment by igrep** [comment]
すみません、忘れてました。。。ありがとうございます。closeします。
