### ISSUE TITLE
Haskell AdC 2017 まとめ 

### ISSUE THREAD

**Issue by reolee** [haskell-jp/blog#71]
遅ればせながら記事を書かせていただきました。
海外からの教授は12/31をデットラインとして設けていたので時差を加味して待ち
返信がない方々に対しては感謝のメールをしました。
あと５記事残ってますが随時あげたら随時プルリクを送らせていただきます。
よろしくお願いします。

Haskellについてのアンケート
https://qiita.com/reotasosan/items/dd4bdcce2633ae19e005

**Comment by igrep** [comment]
https://github.com/haskell-jp/blog/edit/master/preprocessed-site/posts/2017/advent-calendar-2017.md
から直接編集していただけると助かります！
まぁ、全部そろってからでよいですけど

**Comment by reolee** [comment]
ゆうじさん
あけおめです！
修正の件かしこまりました！
ご指摘ありがとうございます。

2018-01-02 9:12 GMT+09:00 Yuji Yamamoto <notifications@github.com>:

**Comment by igrep** [comment]
こちらも古すぎるのでcloseします。
