### ISSUE TITLE
「こういう記事書いて！」って感じの Issue を出せる仕組みを用意したい

### ISSUE THREAD

**Issue by matsubara0507** [haskell-jp/blog#82]
- ○○パッケージの解説記事
- 数学用語と Haskell 用語の対応関係
- ○○の読み方(RWH とか すごいH本 とか割と古典な Haskell 本の今読むならの注意点)

のような記事を書いてほしいという要望をこのリポジトリの Issue で書けると面白いかなぁと思いました。
要望に対して必ず知見があるか分からないので、必ず記事にするかは別にしてあってもいいんじゃないですかね？
そもそも似たような記事があれば、教えて Close すればいいし。

仕組み(流れ)としては

1. Issue の作成
    - 専用の Issue template を用意
        - そこに注釈を書いておく(必ず記事になるとは限りませんとか)
    - 専用のタグの作成しとくので付けてもらう
        - 候補: `Topic Request`
2. 書きたい人が居れば Assign 
3. 書いて PR 
4. Issue Close 

って感じに考えてる。
なので

- [x] Issue template の作成
    - [multi template](https://github.com/blog/2495-multiple-issue-and-pull-request-templates) を使おう
- [x] ラベルの作成
- [x] 「記事希望が出来るようになった」という記事の作成
- [x] igrepによる追記: READMEにも案内を書く

が必要だと思う。

**Comment by igrep** [comment]
いいと思います 👍 
「ネタがない！と言う方は  https://github.com/haskell-jp/blog/issues?q=is%3Aopen+is%3Aissue+label%3A%22Topic+Request%22 から、募集している話題の記事を書いてみるのもいいでしょう。」みたいな導線があると少し敷居が下がるでしょう（し、そのつもりでした。）

**Comment by fumieval** [comment]
クエストシステムいいですね

**Comment by matsubara0507** [comment]
できるようになったって話の記事ですが、これぐらいしか思いつかなかったんですけど、この量でも記事にした方がいいですか？
ないしは他に書くことありますかね？
https://gist.github.com/matsubara0507/dfa703c48634871afbc75d8be90e59b7

**Comment by igrep** [comment]
ありがとうございます！

内容としては十分だと思います。
前置きとかいくつか気になるところはありますが、ここでやるよりもPull requestを送っていただいてからのほうがやりやすいと思うので、出しちゃってください！ 🙏

**Comment by igrep** [comment]
>  igrepによる追記: READMEにも案内を書く

README.md と CONTRIBUTING.md の編集は私がやります。

**Comment by matsubara0507** [comment]
CONTRIBUTING.md で一点、リンクのミスがあったんですけど、それの修正はどうしましょう？
https://github.com/haskell-jp/blog/blame/master/CONTRIBUTING.md#L29 のリンクが正しくは https://github.com/haskell-jp/blog/issues/new?template=topic-request.md&labels="Topic+Request" です。

**Comment by igrep** [comment]
@matsubara0507 お願いします！

**Comment by igrep** [comment]
@matsubara0507 あ、あと、 Topic Request の第1号か第3号ぐらいまでのIssueを作っておいていただけると助かります 🙏

**Comment by matsubara0507** [comment]
あ、やっぱりその方がいいですか？
記事とどっちを先にしようかとは悩んでた。
了解っす 👍

**Comment by igrep** [comment]
順番はお任せしますが、やっぱり何もない状態だと登録しにくいと思うので。。。

**Comment by matsubara0507** [comment]
TR の1-3号を作ったけど Label を付ける権利がぼくに無いので誰かオネシャス

**Comment by igrep** [comment]
Labelつけました。
このままだと不便だと思うので https://github.com/haskell-jp/ のメンバーとしても招待しました。

**Comment by igrep** [comment]
必要なタスクはすべて終わったと見なし、closeします。
