### ISSUE TITLE
Blog title difficult to read

### ISSUE THREAD

**Issue by dfordivam** [haskell-jp/blog#92]
Blogのtitleが読むことが難しいね

![image](https://user-images.githubusercontent.com/681060/36886969-3fa19824-1e32-11e8-8f7a-e71858b07ccd.png)

I propose adding a background to the title like this...

![screenshot_20180302_155813](https://user-images.githubusercontent.com/681060/36887039-983e2a1a-1e32-11e8-815e-9d93f5fcf690.jpeg)

I can send a PR if you like this change..
or we can choose something different..

**Comment by dfordivam** [comment]
Actually the change is very small in default.html

                    <div class="well well-sm" style="opacity: 0.9; background: #2b3a1e;">
                      <h1>$title$</h1>
                      $subHeadingContent$
                    </div>

**Comment by igrep** [comment]
Okay, send a PR, then let's see the change in the preview.

**Comment by dfordivam** [comment]
I have actually put the preview here in the issue itself.. Could you see the inline images in the issue description..

I am not sure if you can render it from a PR. I guess you will have to compile the site to get preview?

**Comment by igrep** [comment]
> I am not sure if you can render it from a PR. I guess you will have to compile the site to get preview?

Yes we can! 😄 
For example, see the comment by haskell-jp-bot in https://github.com/haskell-jp/blog/pull/89 !
That is the link to built preview automatically built by CircleCI.
