### ISSUE TITLE
feed が欲しい

### ISSUE THREAD

**Issue by matsubara0507** [haskell-jp/blog#94]
Hakyll の Feed モジュールでできそう
https://hackage.haskell.org/package/hakyll-4.11.0.0/docs/Hakyll-Web-Feed.html

**Comment by igrep** [comment]
そうか、以前自分のブログでAtom feedを作ったときは面倒くさいなぁと思っていた（し、今もちゃんと動いているか自信がない）けど今は専用のmoduleができてるんですね。

**Comment by igrep** [comment]
Blogtrottrで登録できたことを確認しました！
対応ありがとうございます！
