### ISSUE TITLE
lts-10 系でビルドしたい

### ISSUE THREAD

**Issue by matsubara0507** [haskell-jp/blog#95]
現在 lts-8.5 でビルドをしていますが、理由があるのでしょうか？

**Comment by igrep** [comment]
特に理由はありません！
単に、リポジトリーに必ずビルドできるstack.yamlを置いておけば、いつでも誰でも確実にビルドできるので楽だなぁという程度の理由で置いています！

**Comment by igrep** [comment]
Travis CIのビルドの無事を見届けたらcloseします。

**Comment by igrep** [comment]
OUT OF MEMORYで落ちたっぽいですね。。。 😞 
とりあえずリトライ。
https://travis-ci.org/haskell-jp/blog/builds/352576290

**Comment by matsubara0507** [comment]
こっちにも書いてたのですね。

#100 に書いた out of memory の修正についてですが、自分のとこにフォークして、修正して、 TravisCI を設定して試しました。
https://github.com/matsubara0507/haskell-jp-blog/commit/ead9fdabab6e5ca6b6240037695e80a0c6b7c164
https://travis-ci.org/matsubara0507/haskell-jp-blog/builds/352633812

トークンを設定していないので、最後のデプロイで失敗していますが、問題なく動作しているはずです。

これをどうしましょうか？
PR だとまた動作を確認できないですけど、PR にした方がいいんですかね？

**Comment by igrep** [comment]
https://github.com/haskell-jp/blog/pull/99/commits/603fd64e27cc1cadf2d9d7d00b6e881430186021 みたいに一時的に対象のブランチを増やすか、あるいはこういうケースちょくちょくあると思うので、CIを試す用のブランチを常設しておくかな。。。 🤔

**Comment by matsubara0507** [comment]
あーじゃぁブランチ増やして PR なげますね

**Comment by igrep** [comment]
```yaml
branches:
  only:
    - master
    - '/^test-ci-.*/'
```

こういう風に書き換えれば、 `test-ci-` で始まるすべてのブランチが対象になるはずなので、そうしていただけると助かります。 🙇‍♀️

**Comment by matsubara0507** [comment]
なるほど、賢い
そうします！

**Comment by matsubara0507** [comment]
うーん、でも流石に `test-ci-` というブランチ名だとデプロイできてしまうのまずくないですか？
最後のデプロイだけ `master` 限定にしますか？

**Comment by igrep** [comment]
あくまでもCI関係のみのものを変更するブランチ、と位置づければ、サイトの内容に影響は（普通は）ないはずなんでよいかな、と思っています。

... とここまで書いて気づいたんですが、対象のブランチを増やすPull requestを送ればひょっとしたら第三者のPull requestによってデプロイできてしまうリスクが**多分今も**あるな。。。 😱 

みんなどうしてるんだろう、このあたり。。。 😰

**Comment by igrep** [comment]
とりあえずは現状のまま、デプロイはmasterにマージしてから確認、としますか。。。 😞

**Comment by matsubara0507** [comment]
そうですそうです
`'/^test-ci-.*/'` がマージされたとして、悪意ある人が記事を書き換えて `test-ci-xxx` 何て名前で PR すると、デプロイされてサイトの記事を書き換えてしまうんですよね...

**Comment by igrep** [comment]
少なくともCircle CIは、forkによるpull requestきっかけのビルドはsecret keyを取得できないようになっているんで、そこで防ぐことができるんですが、Travis CIはどうなんだろう。

**Comment by matsubara0507** [comment]
あーそうなんですか

**Comment by matsubara0507** [comment]
ちゃんと取得できないようになってるっぽいですね(そりゃそうか)
https://docs.travis-ci.com/user/environment-variables/
> Encrypted environment variables are not available to pull requests from forks due to the security risk of exposing such information to unknown code.

**Comment by matsubara0507** [comment]
じゃぁ `'/^test-ci-.*/'` を追加して、`test-ci-` でブランチきって PR を送ります。

**Comment by igrep** [comment]
取り急ぎTravis CIの設定と関係しているファイルを確認しました。
ちゃんとSecretな環境変数を参照しているみたいです。 😌 
https://github.com/haskell-jp/blog/blob/a563732b4d32ca67e9917e578796e242633e5bdb/.travis.yml#L64
https://github.com/haskell-jp/blog/blob/a563732b4d32ca67e9917e578796e242633e5bdb/Makefile#L57

**Comment by igrep** [comment]
@matsubara0507 あ、なので
https://github.com/haskell-jp/blog/blob/a563732b4d32ca67e9917e578796e242633e5bdb/.travis.yml#L64
に書いてある、 `[ "$TRAVIS_BRANCH" == master ] &&` という箇所は消しちゃってください。
今はどうせデプロイ時にしかTravis CIは動いていないので、不要なはずです。

**Comment by igrep** [comment]
クローズするの忘れてました。
