### ISSUE TITLE
Circle CI 2.0

### ISSUE THREAD

**Issue by igrep** [haskell-jp/blog#98]
すでに2.0が十分普及していたにもかかわらず惰性でCircle CI 1.0を採用してしまったので、ちゃんとアップグレードする。

**Comment by matsubara0507** [comment]
リミットは 8/31 っすね
see: [CircleCI 1.0 End of Life on August 31, 2018](https://circleci.com/blog/sunsetting-1-0/)

**Comment by igrep** [comment]
Closeし忘れてた 💦
